sudo: required
services:
  - docker

before_install:
  - docker build -t hurtigcodes/docker-react-test -f Dockerfile.dev .

script:
  - docker run hurtigcodes/docker-react-test npm run test -- --coverage
